POSTGRES__DSN: ENC[AES256_GCM,data:V/hHqiIaDl11tjNKqvvUmwuqKkRz4n17RFlFU2TFBXVT9YJyB7veho7JnLPtkibjVnse0WavDmHe+WBwpgkkuchgmRWVfyabwMXxfz4ydmsZ7POASxKH/1wk5yQ53yUT8GCYpT35CKePbZFKetyd86kANtpYEaxMfLHILspexbpBq2+a,iv:LcWTDy1I6UHzc5NcQyt15QFfxiE2nLVCF+KxksUw+mI=,tag:8LFC/dICrClaOURtyyDIqw==,type:str]
AUTH__EDGE_API_KEY: ENC[AES256_GCM,data:KR6NJ630RpK9RyNLvDiMiwfQPvYIaa6khSx2uLM4GHRHlOd0FffqPtiDJB4sKvpNE9moeVU8BrzAp0iIZ5f7KQ==,iv:PR8VUq1FpdbGhu0w2ZD4AJ9FPhZcJtZVL/QAEMR0zw8=,tag:U0UyOQP8U5O6nTkUGTsMOg==,type:str]
ADMIN__PASSWORD: ENC[AES256_GCM,data:cA/G5X7BMZWYXFFN7fvKvVsiS6VI8iRG5D2cwbJ7Yzo=,iv:sr78huk7tluKchVvTwYrxowvl3w+mLMD4aS3bob0J70=,tag:GhdURsgsXT86KVrK4NMYVg==,type:str]
ADMIN__SECRET: ENC[AES256_GCM,data:F8oU0yULH8Cx16eeoYDMmCbOwOViyU0uG8rAe2U4kpAgForggHXpIWeUroFMD1RhKtfaUDmP9/+CbsJX1R+XUg==,iv:k+yrRHdgWoAxaUEhxxewEHYniBH0k/yx/EoU3/jodRQ=,tag:4Vd6Nm9lgMOiRQ7n/9SPzg==,type:str]
sops:
    lastmodified: "2026-05-03T10:39:32Z"
    mac: ENC[AES256_GCM,data:+97dS5SfrltkBWsqRtO0p839YENwYA+7u0RvC1mdSWdzW5kuLMXUA2/YF/8UVT1OsB/SfNlZ6CeozkM+RlVs3Ejh7j5n0iRnpiFzWaJgyeh5CEEpRkBF0DzsOfHVNMKIfzh3K31cwSdDbh7q5N0B+ADpBjqeyaoes9E0bAGFKt0=,iv:y0zTrw9/VrV37g/LtQUbv+CFAu2RXmpq3H1S1V/FgX0=,tag:HNh78aBlnzoYg4TzVV1Rcg==,type:str]
    pgp:
        - created_at: "2026-05-03T10:39:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwuv5h3yTKwCAQ/+OMKOzG5Ft83+LkacEREWVuOBUlR9Cr0cwRxb7i+0XVwV
            D8fx3FrBBA3d0/VfJbwnM1NBoMFsE7I+vx7Ws5OpdvI8BvwpjyvMZqhWqPJId6fL
            Oc7tKm9qjRSHO9drnzxYvUtMd+749Etr6uKVs6zVao2e4WvykqvAyapoWwMG4dpd
            THf1JNO3/rBHc3bNLgKjX4JiOoqavZvrgG2ID3uchQbV1mNTk+yS40oLrs/4p7Xk
            lImpUaFhBS8wFm4yXmtpJ5qkM3sMJF5B6plSeqWq+dmS7/m7SQV9PvHjhqBfE5hR
            kZ7800USkG673coTN51X2n2fhuJiVa5Ed46JWGHC5s8ldITWBeK+7CESV85kUgz4
            DxwGKGYf+NjJgbBpYeufgFmNMfzQRTbqoUseQBerUHnZhQzuA+XKaumGk5bkbLAK
            JJ/qugqZg4s4WlHAaQiWrpEZsdDn40DC3Rr6pNQu5c7RiSUYXMdSnQW3mo2/u8U1
            SRWGGZ9La2DgsrPJj0r8JFJ/phtvB2sbk7du8cBV8/3J1YNd2Iyz4uWcJ2ynMCgk
            MYb9gf/ay8NSXii2CdIqWCgzBlA6c8DglIb/LF+JtH7we+UZr0z8rDYCHNZRKuwG
            79jtNWJZVsfQEzZ5RblhTrPAsuOX47nWPoUz/B4L+IgXbULr2t2HHK2UDT+SHyjU
            aAEJAhCy84k585J/YdTtcrxgvvOMprf9jJ48ZxLdW8DiwTiFYjbOAuTqz8ELzgVN
            J/wDy6THeI3NyjMvf3L3FbO81NOLS/2qT3joBgs8Ru6wzd//+Xjh1VJXfcQKpiPL
            CzPEUlhkdlA4
            =phgk
            -----END PGP MESSAGE-----
          fp: 306DECA1437FDD721E2488D834D0A486928B97DE
        - created_at: "2026-05-03T10:39:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DIvUZMTn43qsSAQdA0fDFAiMEaB7LDS0UWrGjki7lWV2E1KTL+9q0uO/BKAQw
            j9wcty0RfK+Rt1d/KQ/yHxhyF6ehRBuLb31zbUVd2CpkUn12GW69ij44L1UAznS+
            1GgBCQIQe5ZWFEQs2IlRzxrDzK43a2LtuUwsex7aXOXSIMwsJRC4TdS3rT0AQRkP
            nTNQPYtYSr8lWR8I6b6p1zui3hQqeY7SklvZaLTqfZYQRNDQTc2iXFg0EfML+pFO
            UJijta8xO+TytA==
            =hb8N
            -----END PGP MESSAGE-----
          fp: 30E34672A3B49BBB6509A1AD6A26A772A2BEE114
    unencrypted_suffix: _unencrypted
    version: 3.10.2
