POSTGRES__PASSWORD: ENC[AES256_GCM,data:zMTDkPDMjPG0t7n3SlNEskdVnoOiF20FW5yJMuBW0aL4aHhWUPPsdeejGvAj6wjEmaqZYJqseVVSQ/UYcbZTZQ==,iv:rk5O0qKscLwi6pifla5AbIzVDNBEcleApXTlZsLHG88=,tag:VAvx1Q9Zftjvm7JP4A1R0w==,type:str]
AUTH__EDGE_API_KEY: ENC[AES256_GCM,data:S6xmmyaP/O5ZuIYnUKjgb4HUsf5ReU9DDn9PM93fsLOc20iA/MXTAJwpPuPAkWp/1osUFmYdc9aq+BKf984Wng==,iv:IqZkEvsj/GkA82TJd06cR5cjIAVYD1IaLDyBv1m+r8c=,tag:C5CePR++v5+DoG5CvI15Qg==,type:str]
sops:
    lastmodified: "2026-03-15T15:06:24Z"
    mac: ENC[AES256_GCM,data:BVZEeuZuClJ+YUpwCJf72K/IgBPrQ6HWnGTp0H82tznlOjSiS1A/CJAFl625sZ5FAk9273OuU3Q/wktpAY8GgszFFu6DHKNkSZWbPuR33AcMjQU89V5yVqNjTQBpzPd4ZaZ1qzpQwJGCxskyLvW2jvNA38zATjPGC6A5t6jeowE=,iv:rIczlMF28b08BXMVm7umKhAPC7aTWZxpqgZTMiGg1Wg=,tag:Van3ntGUsiI6BTJxKsUadg==,type:str]
    pgp:
        - created_at: "2026-03-15T15:06:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQILAwuv5h3yTKwCAQ/496UBuH2VBTAZC39WsTJv1V0UhpNDl5dDpDjcUGT6WACK
            0ijNlvjkKWB7iAYWFWtqMZyIUZaB9MDQ6P2jEOTWhU0wKn7u0sfrUIIQX+7J+gWv
            rd/L4wtIqaVQetSwYsuzhCBIBXsh2XlfVFnlGlbQvY/nJP+6DgVpo1NAPPGga045
            9rodiAhiBdeFpIRd3PHM0Ie+8XDc3/LvD63ynZYqIMZR135c5AWOe5zDIvJofoO+
            01lHVxef1GNoG8EXylViiu1fFTwsCXZhIFHKjCqwvICsyI+r7EOw73hdYIBNTGe2
            pU+Y1EYeV6EEJWDTymXl7ZCGDFyuQ725LT1jeAG7s8geSu8405DaRH6hoTP6cknO
            LVnofPDfvPR/x09C/zXL2QObbXPvcgQmYNuIBetMy+uYgwUvCju4hXkTJK4tWSp8
            Ibzb98am2Kto8zs+cC6E+8UgIipnb7+GF9WG88cikWzDUKIqHaAfUM2WeQvKUadw
            VGh4TYNTkgzQmQZFlrysbmfRAmzbDis/2mB+lsBXazOJjZMPmZgiQtzgEsPe0Gw4
            /7Q7zNfDWVbbJDI3Sp6NyXuV4qa0KjV63aa5VHeVEdhMF7t0ol/lA77VR2VQv80/
            Td+qDU4qLIrdwWq+e+JUzKbAaVBzfuKC7ZuN9EO7Np8pDTJtq2q1PQQMQvJDy9Ro
            AQkCECR3eknDj5Q5yxLL/vbMpI1XXudM9FJOL3rDgYALOlGesrtn1KDys9UVwizF
            SXDn4BIM59D1qF5x/SnU50QPeGy5isGgi+RyaxKB5+qjLjbYkgALLUGK2R7SX7e2
            9hR5jLEzvt4=
            =DoQg
            -----END PGP MESSAGE-----
          fp: 306DECA1437FDD721E2488D834D0A486928B97DE
        - created_at: "2026-03-15T15:06:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DIvUZMTn43qsSAQdAqkJTunuYxH7U5HnRrVgMXFi7lKKVXhBWWWZdRy0xQn8w
            NtZwsqwjqYt+grmyqkJNhnv3NlYQ9G9NSt5ewUUVk55wVJRSsvwIJ6DmW+9aZ/su
            1GgBCQIQGi8L9HqR3E0kjaCqt3hf3Pv4a7X1hB+htEa/vNOQ2CDAP8gUYOz/GAHw
            a4Askhl6I4ON+wQI+mteAx824Uzs4TwP2qIe/T7GSycAxkLfyWmPKEFpD1P+Nk1Z
            rRXxnE8YGgwaog==
            =0DyD
            -----END PGP MESSAGE-----
          fp: 30E34672A3B49BBB6509A1AD6A26A772A2BEE114
    unencrypted_suffix: _unencrypted
    version: 3.10.2
