container:
  name: api
  port: 5100
  command: ["uvicorn"]
  args:
    [
      "app.entrypoints.api:create_app",
      "--factory",
      "--proxy-headers",
      "--forwarded-allow-ips=*",
      "--workers",
      "1",
      "--host",
      "0.0.0.0",
      "--port",
      "5100",
    ]

ingress:
  path: /

livenessProbe:
  exec:
    command:
      - sh
      - -c
      - celery -A app.entrypoints.worker:app inspect ping -d celery@$HOSTNAME
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
